from __future__ import annotations

import pathlib
import subprocess
import sys
import tempfile
import textwrap
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]
CHECKER = ROOT / "scripts" / "fleet_contract.py"


class FleetContractTests(unittest.TestCase):
    def make_rust_repo(self) -> pathlib.Path:
        temp = tempfile.TemporaryDirectory()
        self.addCleanup(temp.cleanup)
        repo = pathlib.Path(temp.name)
        subprocess.run(["git", "init", "-q", str(repo)], check=True)
        subprocess.run(
            ["git", "-C", str(repo), "config", "user.email", "test@example.com"],
            check=True,
        )
        subprocess.run(
            ["git", "-C", str(repo), "config", "user.name", "Test"],
            check=True,
        )

        (repo / "src").mkdir()
        (repo / "docs").mkdir()
        (repo / "src/main.rs").write_text("//! Test crate.\nfn main() {}\n")
        (repo / "rust-toolchain.toml").write_text(
            '[toolchain]\nchannel = "1.97.1"\ncomponents = ["rustfmt", "clippy"]\n'
        )
        (repo / "Cargo.toml").write_text(
            textwrap.dedent(
                """\
                [package]
                name = "fixture"
                version = "0.1.0"
                edition = "2024"
                description = "Fixture repository."
                license = "MIT"
                repository = "https://github.com/dinglebear-ai/fixture"
                homepage = "https://github.com/dinglebear-ai/fixture"

                [lints]
                workspace = true

                [workspace]

                [workspace.lints.rust]
                missing_crate_level_docs = "deny"
                unsafe_op_in_unsafe_fn = "deny"

                [workspace.lints.rustdoc]
                broken_intra_doc_links = "deny"
                invalid_codeblock_attributes = "deny"
                invalid_html_tags = "deny"
                bare_urls = "warn"
                private_intra_doc_links = "warn"
                redundant_explicit_links = "warn"
                unescaped_backticks = "warn"

                [workspace.lints.clippy]
                missing_safety_doc = "deny"
                """
            )
        )
        (repo / "Cargo.lock").write_text(
            "# This file is automatically @generated by Cargo.\nversion = 4\n"
        )
        (repo / "CLAUDE.md").write_text("# Fixture\n")
        (repo / "AGENTS.md").symlink_to("CLAUDE.md")
        (repo / "GEMINI.md").symlink_to("CLAUDE.md")
        (repo / ".env.example").write_text("")
        (repo / "README.md").write_text("# Fixture\n\nFixture repository.\n")
        (repo / "docs/guide.md").write_text(
            "---\n"
            "title: Guide\n"
            "created: 2026-07-30\n"
            "updated: 2026-07-30\n"
            "---\n\n"
            "# Guide\n"
        )
        subprocess.run(["git", "-C", str(repo), "add", "."], check=True)
        subprocess.run(
            ["git", "-C", str(repo), "commit", "-qm", "test: fixture"],
            check=True,
        )
        return repo

    def run_check(self, repo: pathlib.Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [
                sys.executable,
                str(CHECKER),
                "check",
                "--repo",
                str(repo),
                "--profile",
                "rust",
            ],
            text=True,
            capture_output=True,
            check=False,
        )

    def test_compliant_rust_repository_passes(self) -> None:
        result = self.run_check(self.make_rust_repo())
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("fleet contract valid", result.stdout)

    def test_reports_independent_contract_violations(self) -> None:
        repo = self.make_rust_repo()
        (repo / "rust-toolchain.toml").unlink()
        (repo / "AGENTS.md").unlink()
        (repo / "AGENTS.md").write_text("# not a symlink\n")
        cargo = (repo / "Cargo.toml").read_text()
        (repo / "Cargo.toml").write_text(
            cargo.replace('edition = "2024"', 'edition = "2021"').replace(
                "https://github.com/dinglebear-ai/fixture",
                "https://github.com/jmagar/fixture",
            )
        )
        (repo / "install.sh").write_text(
            "#!/bin/sh\ncase arm64 in arm64) exit 0;; esac\n"
        )
        subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True)

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 1)
        for check in (
            "toolchain-pinned",
            "edition-2024",
            "symlink-convention",
            "no-stale-org-refs",
            "no-arm-contract",
        ):
            with self.subTest(check=check):
                self.assertIn(check, result.stdout)

    def test_docs_frontmatter_checks_tracked_markdown_only(self) -> None:
        repo = self.make_rust_repo()
        (repo / "docs/guide.md").write_text("# Missing metadata\n")
        (repo / "docs/untracked.md").write_text("# Scratch\n")

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 1)
        self.assertIn("docs-frontmatter: docs/guide.md", result.stdout)
        self.assertNotIn("docs/untracked.md", result.stdout)

    def test_imported_and_generated_docs_do_not_require_fleet_frontmatter(self) -> None:
        repo = self.make_rust_repo()
        for directory in (
            "archive",
            "generated",
            "perf",
            "pipeline-unification",
            "plans",
            "reference",
            "references",
            "reports",
            "sessions",
            "superpowers",
            "upstream",
            "vendor",
        ):
            path = repo / "docs" / directory / "reference.md"
            path.parent.mkdir(parents=True)
            path.write_text("# External reference\n")
        subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True)

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_repository_can_exclude_frozen_docs_with_explicit_globs(self) -> None:
        repo = self.make_rust_repo()
        frozen = repo / "docs/snippets/smoke-output.md"
        frozen.parent.mkdir(parents=True)
        frozen.write_text("# Captured output\n")
        (repo / ".fleet-contract.toml").write_text(
            '[docs]\nfrontmatter-exclude = ["docs/snippets/*-output.md"]\n'
        )
        subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True)

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_repository_doc_exclusions_do_not_hide_other_maintained_docs(self) -> None:
        repo = self.make_rust_repo()
        snippets = repo / "docs/snippets"
        snippets.mkdir()
        (snippets / "smoke-output.md").write_text("# Captured output\n")
        (snippets / "maintained.md").write_text("# Missing metadata\n")
        (repo / ".fleet-contract.toml").write_text(
            '[docs]\nfrontmatter-exclude = ["docs/snippets/*-output.md"]\n'
        )
        subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True)

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 1)
        self.assertIn("docs-frontmatter: docs/snippets/maintained.md", result.stdout)

    def test_memory_and_readme_docs_do_not_require_frontmatter(self) -> None:
        repo = self.make_rust_repo()
        (repo / "docs/CLAUDE.md").write_text("# Repository memory\n")
        (repo / "docs/AGENTS.md").symlink_to("CLAUDE.md")
        (repo / "docs/GEMINI.md").symlink_to("CLAUDE.md")
        (repo / "docs/README.md").write_text("# Documentation index\n")
        subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True)

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_compose_prose_is_not_treated_as_a_compose_manifest(self) -> None:
        repo = self.make_rust_repo()
        notes = repo / "notes"
        notes.mkdir()
        (notes / "android-compose-migration.md").write_text(
            "Historical link: https://github.com/jmagar/fixture\n"
        )
        subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True)

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_dependency_ranges_do_not_count_as_exact_pins(self) -> None:
        repo = self.make_rust_repo()
        with (repo / "Cargo.toml").open("a") as manifest:
            manifest.write('\n[dependencies]\nrmcp = "2.2.0"\n')
        (repo / "Cargo.lock").write_text(
            textwrap.dedent(
                """\
                version = 4

                [[package]]
                name = "rmcp"
                version = "2.2.0"
                """
            )
        )
        subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True)

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 1)
        self.assertIn("deps-exact-pinned: Cargo.toml", result.stdout)

    def test_explicit_unsafe_ffi_boundary_may_opt_out_of_workspace_lints(self) -> None:
        repo = self.make_rust_repo()
        cargo = (
            (repo / "Cargo.toml")
            .read_text()
            .replace(
                "[workspace.lints.rust]\n",
                '[workspace.lints.rust]\nunsafe_code = "forbid"\n',
            )
        )
        (repo / "Cargo.toml").write_text(cargo)
        ffi = repo / "crates/ffi"
        (ffi / "src").mkdir(parents=True)
        (ffi / "src/lib.rs").write_text("//! Sanctioned FFI boundary.\n")
        (ffi / "Cargo.toml").write_text(
            textwrap.dedent(
                """\
                [package]
                name = "fixture-ffi"
                version = "0.1.0"
                edition = "2024"
                description = "Sanctioned FFI boundary."
                license = "MIT"
                repository = "https://github.com/dinglebear-ai/fixture"
                homepage = "https://github.com/dinglebear-ai/fixture"

                [package.metadata.fleet]
                workspace-lints-exception = "unsafe-ffi"

                [lints.rust]
                unsafe_code = "allow"
                """
            )
        )
        subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True)

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_non_ffi_package_cannot_opt_out_of_workspace_lints(self) -> None:
        repo = self.make_rust_repo()
        cargo = (
            (repo / "Cargo.toml")
            .read_text()
            .replace(
                "[lints]\nworkspace = true",
                '[lints.rust]\nunsafe_code = "allow"',
            )
        )
        (repo / "Cargo.toml").write_text(cargo)
        subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True)

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 1)
        self.assertIn("workspace-lints: Cargo.toml", result.stdout)

    def test_description_must_match_present_repository_surfaces(self) -> None:
        repo = self.make_rust_repo()
        (repo / "README.md").write_text(
            "# Fixture\n\nA different repository description.\n"
        )
        subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True)

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 1)
        self.assertIn("description-consistency: README.md", result.stdout)

    def test_tracked_ignored_secret_file_is_rejected(self) -> None:
        repo = self.make_rust_repo()
        (repo / ".gitignore").write_text(".env\n")
        (repo / ".env").write_text("SECRET=fixture\n")
        subprocess.run(["git", "-C", str(repo), "add", ".gitignore"], check=True)
        subprocess.run(
            ["git", "-C", str(repo), "add", "-f", ".env"],
            check=True,
        )

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 1)
        self.assertIn("tracked-path-hygiene: .env", result.stdout)

    def test_env_example_key_must_have_a_consumer(self) -> None:
        repo = self.make_rust_repo()
        (repo / ".env.example").write_text("UNUSED_TOKEN=\n")
        subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True)

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 1)
        self.assertIn("env-schema: .env.example", result.stdout)

    def test_bootstrap_template_memory_links_are_created_by_installer(self) -> None:
        repo = self.make_rust_repo()
        template = repo / "bootstrap/common"
        template.mkdir(parents=True)
        (template / "CLAUDE.md").write_text("# Generated memory\n")
        subprocess.run(["git", "-C", str(repo), "add", "-A"], check=True)

        result = self.run_check(repo)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)


if __name__ == "__main__":
    unittest.main()
